import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cornwall, ON HVAC Services - Get a Quote! | Wylie Mechanical",
  description: "Cornwall, ON HVAC services by Wylie Mechanical. Get expert heating and air conditioning installation, repair, and maintenance. Call us now!",
};

export default function Page() {
  return (
    <div 
      className="prose prose-lg max-w-none text-body migrated-content" 
      dangerouslySetInnerHTML={{ __html: `<div data-elementor-type="wp-page" data-elementor-id="15788" class="elementor elementor-15788" data-elementor-post-type="page"><section class="elementor-section elementor-top-section elementor-element elementor-element-1d446dc elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="1d446dc" data-element_type="section" data-e-type="section"><div class="elementor-container elementor-column-gap-default"><div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-0726d8e" data-id="0726d8e" data-element_type="column" data-e-type="column"><div class="elementor-widget-wrap elementor-element-populated"><div class="elementor-element elementor-element-ed15b2b elementor-widget elementor-widget-heading" data-id="ed15b2b" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div class="elementor-widget-container"><h2 class="elementor-heading-title elementor-size-default">Our HVAC Services in Cornwall, Lancaster, Alexandria, ON, and Surrounding Areas</h2></div></div><div class="elementor-element elementor-element-015ca19 elementor-widget elementor-widget-image" data-id="015ca19" data-element_type="widget" data-e-type="widget" data-widget_type="image.default"><div class="elementor-widget-container"><img alt="Goodman HVAC units including air conditioners and furnaces, showcasing options for improving indoor air quality and comfort in homes." fetchpriority="high" decoding="async" width="570" height="353" src="https://www.wyliemechanical.com/wp-content/uploads/2021/10/fm-products.png" class="attachment-large size-large wp-image-16367"   title="Our HVAC Services In Cornwall, ON" ></div></div><div class="elementor-element elementor-element-05e99ee elementor-widget elementor-widget-text-editor" data-id="05e99ee" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default"><div class="elementor-widget-container"><p><strong>Our HVAC Services includes:</strong></p><ul><li><a href="/ductless-mini-splits-services-cornwall-on/">Ductless Mini-Splits</a></li><li><a href="/water-heaters-cornwall-on/">Water Heaters</a></li><li><a href="/gas-lines-cornwall-on/">Gas Lines</a></li></ul></div></div><div class="elementor-element elementor-element-441069f elementor-widget elementor-widget-heading" data-id="441069f" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div class="elementor-widget-container"><h3 class="elementor-heading-title elementor-size-default"><a href="/contact-us/">Contact Us</a> Today for Our HVAC Services in Cornwall, Lancaster, Alexandria, ON, and Surrounding Areas</h3></div></div></div></div></div></section></div>` }} 
    />
  );
}
